export const state = {
  player: null,
  cursors: null,
  jumpKey: null,
  shootKey: null,
  wasdKeys: null,
  restartKey: null,
  pauseKey: null,

  platforms: null,
  coins: null,
  spikes: null,
  skeletons: null,
  bosses: null,
  bullets: null,
  backgroundImage: null,
  cloudsImage: null,

  score: 0,
  currentNickname: '',
  ranking: [],
  playerLives: 3,
  heartSprite: null,
  isLifeTransition: false,
  scoreText: null,
  levelText: null,
  bossHpText: null,
  gameOverText: null,

  isGameOver: false,
  isPaused: false,
  hasGameStarted: false,
  currentLevelIndex: 0,
  playerSpawnPoint: null,
  elapsedTimeSeconds: 0,
  lastTickMs: 0,
  lastShotMs: 0,
  shotCooldownMs: 450,
  playerFacing: 1,
  nextBossAttackMs: 0,
  nextPlayerDamageMs: 0,
  playerDamageCooldownMs: 1100,

  winScreen: null,
  mainMenu: null,
  pauseOverlay: null,
  boss: null,
  bossHealth: 0,
  bossMaxHealth: 20,
  bossHitsTaken: 0,
  lastBossDamageMs: 0,
  bossDamageCooldownMs: 120,

  playerPlatformCollider: null,
  coinPlatformCollider: null,
  skeletonPlatformCollider: null,
  bulletPlatformCollider: null,
  playerBossCollider: null,
  playerCoinOverlap: null,
  playerSpikeOverlap: null,
  playerSkeletonCollider: null,
  bulletSkeletonOverlap: null,
  bulletBossOverlap: null,
};
